[package]
name = "geostationary"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["modules/network"]

[dependencies]
bevy = { version = "0.12", features = [] }

network = { path = "modules/network" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
