[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = [] }
bevy_quinnet = { version = "0.9" }
serde = { version = "1.0", features = ["derive"] }
